packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'

onlyBuiltDependencies:
  - '@swc/core'
  - better-sqlite3
  - esbuild
  - sharp
